[package]
name = "todo"
version = "1.2.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inquire = { version = "0.4", features = ["editor"] }
clap = { version = "4", features = ["derive"] }
colored = "2"
